# Application Argo CD "concierge" : l'IA mÃ©tier (Ollama, Qdrant, rag-service).
# MÃªme namespace que staybook : les services doivent se voir par leur nom DNS.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concierge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Roulitau/TP-Argo.git
    targetRevision: HEAD
    path: apps/concierge
  destination:
    server: https://kubernetes.default.svc
    namespace: staybook
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
